"""Schema

Revision ID: b6b6414f1b16
Revises: 
Create Date: 2026-08-09 13:26:27.426132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b6414f1b16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id_ibge', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id_ibge')
    )
    op.create_table('usuarios_admin',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'GESTOR_MUNICIPAL'"), nullable=False),
    sa.CheckConstraint("role IN ('GESTOR_ESTADUAL', 'GESTOR_MUNICIPAL', 'ADMIN')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vacinas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('alta_complexidade', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('alertas_completude',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('referencia_ano', sa.SmallInteger(), nullable=False),
    sa.Column('referencia_mes', sa.SmallInteger(), nullable=False),
    sa.Column('municipio_id', sa.String(length=7), nullable=True),
    sa.Column('total_observado', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ABERTO'"), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ABERTO', 'INVESTIGANDO', 'RESOLVIDO', 'FALSO_POSITIVO')", name='chk_alerta_status'),
    sa.CheckConstraint('referencia_mes BETWEEN 1 AND 12', name='chk_mes_valido'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id_ibge'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('valores_antigos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valores_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("acao IN ('UPDATE', 'DELETE')", name='chk_log_acao'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios_admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auditoria_registro', 'log_auditoria', ['tabela', 'registro_id'], unique=False)
    op.create_table('registros_vacinacao',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('data_vacinacao', sa.Date(), nullable=False),
    sa.Column('idade', sa.SmallInteger(), nullable=True),
    sa.Column('vacina_id', sa.Integer(), nullable=True),
    sa.Column('municipio_residencia_id', sa.String(length=7), nullable=True),
    sa.Column('municipio_vacina_id', sa.String(length=7), nullable=False),
    sa.Column('teve_deslocamento', sa.Boolean(), nullable=True),
    sa.Column('quantidade', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status_dado', sa.String(length=25), server_default=sa.text("'VALIDO'"), nullable=False),
    sa.CheckConstraint("(idade IS NULL) OR (idade >= 0 AND idade <= 110) OR (status_dado = 'DADO_INCONSISTENTE')", name='chk_idade_valida'),
    sa.CheckConstraint("status_dado IN ('VALIDO', 'DADO_INCONSISTENTE', 'DESLOCAMENTO_INDETERMINADO')", name='chk_status_dado'),
    sa.CheckConstraint('quantidade > 0', name='chk_quantidade_positiva'),
    sa.ForeignKeyConstraint(['municipio_residencia_id'], ['municipios.id_ibge'], ),
    sa.ForeignKeyConstraint(['municipio_vacina_id'], ['municipios.id_ibge'], ),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registro_data', 'registros_vacinacao', ['data_vacinacao'], unique=False)
    op.create_index('idx_registro_local', 'registros_vacinacao', ['municipio_vacina_id'], unique=False)
    op.create_index('idx_registro_residencia', 'registros_vacinacao', ['municipio_residencia_id'], unique=False)
    op.create_index('idx_registro_vacina', 'registros_vacinacao', ['vacina_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_registro_vacina', table_name='registros_vacinacao')
    op.drop_index('idx_registro_residencia', table_name='registros_vacinacao')
    op.drop_index('idx_registro_local', table_name='registros_vacinacao')
    op.drop_index('idx_registro_data', table_name='registros_vacinacao')
    op.drop_table('registros_vacinacao')
    op.drop_index('idx_auditoria_registro', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('alertas_completude')
    op.drop_table('vacinas')
    op.drop_table('usuarios_admin')
    op.drop_table('municipios')
    # ### end Alembic commands ###
