"""extend status_dado length

Revision ID: c5c1364dfc81
Revises: b6b6414f1b16
Create Date: 2026-08-09 14:10:52.900585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c1364dfc81'
down_revision: Union[str, Sequence[str], None] = 'b6b6414f1b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'registros_vacinacao',
        'status_dado',
        type_=sa.String(length=30),
        existing_type=sa.String(length=25),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'registros_vacinacao',
        'status_dado',
        type_=sa.String(length=25),
        existing_type=sa.String(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
